Vagrant.configure("2") do |config|
  config.vm.define "static" do |static|
    static.vm.box = "jaca1805/debian12" 
    static.vm.network "private_network", ip: "192.168.33.13"
    static.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end
  config.vm.define "httpd" do |httpd|
    httpd.vm.box = "jaca1805/debian12" 
    httpd.vm.network "private_network", ip: "192.168.33.14"
    httpd.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end
    config.vm.define "postgresql" do |postgresql|
    postgresql.vm.box = "jaca1805/debian12" 
    postgresql.vm.network "private_network", ip: "192.168.33.15"
    postgresql.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end

end
