- name: Install and configure HTTPd server
  hosts: 4.205.28.253
  become: yes
  become_user: maximefrank

  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
